export const VIEW_BRANCH_DATA = "VIEW_BRANCH_DATA";
export const VIEW_UNIQUEBRANCH_DATA = "VIEW_UNIQUEBRANCH_DATA";
export const VIEW_AVAILABLE_BRANCHES = "VIEW_AVAILABLE_BRANCHES";
export const VIEW_UPDATED_NOTIFICATION = "VIEW_UPDATED_NOTIFICATION";
export const POST_BRANCH_DATA = "POST_BRANCH_DATA";